### ISSUE TITLE
icon ideas and name suggestion for main app icon and name  

### ISSUE THREAD

**Issue by Umer-naseer** [Saqib-db/Reminder_iOS#4]
@moranciejr @Saqib-db/owners 
i am just uploading some icon as prototype plz check it and make suggestions in comments 
1x
![1x_76-76_tt_1](https://cloud.githubusercontent.com/assets/10264004/8197062/f9605904-14ac-11e5-917e-f64dd83f7ce9.jpg)
![1x_76-76_tt_2](https://cloud.githubusercontent.com/assets/10264004/8197063/f96112d6-14ac-11e5-9d4f-b7689e5613a2.jpg)
![1x_76-76_tt_3](https://cloud.githubusercontent.com/assets/10264004/8197064/f964ef00-14ac-11e5-86d3-868d78cae55f.jpg)
![1x_76-76_tt_4](https://cloud.githubusercontent.com/assets/10264004/8197065/f965838e-14ac-11e5-8f7a-5d96309d52b9.jpg)
![1x_76-76_tt_5](https://cloud.githubusercontent.com/assets/10264004/8197066/f9682ad0-14ac-11e5-8bde-1d6fc5023f0b.jpg)
2x
![1x_120-120_tt_1](https://cloud.githubusercontent.com/assets/10264004/8197070/08c454ea-14ad-11e5-80c3-651824c26bb8.jpg)
![1x_120-120_tt_2](https://cloud.githubusercontent.com/assets/10264004/8197071/08c7d674-14ad-11e5-8506-f7134ea0a737.jpg)
![1x_120-120_tt_3](https://cloud.githubusercontent.com/assets/10264004/8197072/08c93fa0-14ad-11e5-94fc-66ca787fa462.jpg)
![1x_120-120_tt_4](https://cloud.githubusercontent.com/assets/10264004/8197073/08cba15a-14ad-11e5-9f8c-67222c331416.jpg)
![1x_120-120_tt_5](https://cloud.githubusercontent.com/assets/10264004/8197074/08ce04ae-14ad-11e5-905e-9201e7d3fd97.jpg)

**Comment by moranciejr** [comment]
Hmmm What if you keep the "T" and put the Clock hands on it.  Call it Time Tracker. Use only one T for two words.  Or name it Time manager. Or something like that...what do you think?

**Comment by Umer-naseer** [comment]
time tracker sounds awesome 
now i am just uploading some icons with clock as you wanted and how they look in app store and iPhone
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
![s_1](https://cloud.githubusercontent.com/assets/10264004/8218830/13b81488-155f-11e5-821d-89faab7af4a0.png)
![s_2](https://cloud.githubusercontent.com/assets/10264004/8218831/13ba61c0-155f-11e5-835e-af47dda7e32a.png)
![s_3](https://cloud.githubusercontent.com/assets/10264004/8218832/13bd8148-155f-11e5-851d-f371609d5849.png)
![tt_123_qwe-02](https://cloud.githubusercontent.com/assets/10264004/8218833/13bf7cb4-155f-11e5-9de7-3b3f37a5de5f.png)
![tt_t2-02](https://cloud.githubusercontent.com/assets/10264004/8218834/1400cb1a-155f-11e5-9b41-bdbac3c7d7c9.png)
![tt1-02](https://cloud.githubusercontent.com/assets/10264004/8218835/140304b6-155f-11e5-9108-07f2105b33d1.png)

**Comment by moranciejr** [comment]
I like the second from the bottom. But the "hands sort of look like a backwards L.   I also like the third one from the bottom with the red and yellow, possibly better
